### ISSUE TITLE
Add a feature that can send raw http request data in a window

### ISSUE THREAD

**Issue by NEX-S** [0140454/hackbar#18]
can hackbar add a feature that allows us to send raw HTTP request data in a window or panel? like burpsuite's repeater but the response result of the server is rendered by our browser. This feature will be fantastic if it can be implemented :D

**Comment by 0140454** [comment]
Maybe I can make HackBar accept raw HTTP request from user.
However, due to the implementation limit, there are some limitations:
* Only GET and POST verb can be used.
* HTTP version in request is ignored.
* `Content-type` only can be those listed in `enctype` combobox.
  In the other words, you cannot use `text/plain`.
* Request body may be modified.
  If you want to send a JSON but there is no equal sign in the body, HackBar will try to add some garbage value just like now.

If you can accept these limitations, I will try to implement it but there is no ETA now.

**Comment by 0140454** [comment]
Before implementing it, I would like to known your scenario.

Is "loading a raw request and modifying it using current UI" acceptable to you? Like the following video, but type a raw request instead of cURL command.

https://user-images.githubusercontent.com/1191368/193438115-75fc6318-d30c-4596-8b2f-23a82b850277.mp4

Or you really need a big textarea to type everything manually? If it's true, could you tell me your scenario to let me think how to make it more user-friendly?

**Comment by 0140454** [comment]
> The left part can send a raw HTTP request
> The right part can receive the raw HTTP response.

If I doesn't misunderstand your comment, what you want is a Fetch mode, which is implemented using `fetch` API, instead of Page mode?
_"Page mode" is just a temporary name. Maybe you can give a nicer name._

* Fetch mode
  * Use [`fetch`](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API) API to get response, transform [`Response`](https://developer.mozilla.org/en-US/docs/Web/API/Response) into a raw HTTP response and show it in the right panel
  * You can do anything supported by `fetch`
* Page mode (current behaviour)
  * Use different methods to implement GET/POST
    * GET: WebExtension API `chrome.tabs.update`
    * POST: Use `chrome.tabs.executeScript` to insert a `form` HTML element and submit it automatically
  * Only support GET/POST method, and has some limitation of POST body

> Every time we press the EXECUTE button, the new panel will auto-load the last HTTP raw request into the bigtext area.
> When we are in the new panel, the EXECUTE button can send the raw HTTP request.

Sorry that I cannot imagine the complete UI flow.
I think EXECUTE button is used to perform a request, not to load request.

> And I think maybe hackbar can move some encoding / decoding stuff into the right-click mouse panel.
> It can save some space on the top bar and it's more user-friendly than the top bar.

This is a good advice.
But I think it will not land in next release since it is needed to be designed.

**Comment by 0140454** [comment]
> **The left part can send a raw HTTP request**
> **The right part can receive the raw HTTP response.**

If I doesn't misunderstand your comment, what you want is a Fetch mode, which is implemented using `fetch` API, instead of Page mode?
> "Page mode" is just a temporary name. Maybe you can give a nicer name.

* Page mode (current behaviour)
  * Use different methods to implement GET/POST
    * GET: WebExtension API `chrome.tabs.update`
    * POST: Use `chrome.tabs.executeScript` to insert a `form` HTML element and submit it automatically
  * Only support GET/POST method, and has some limitation of POST body
  * The response is rendered in the page
* Fetch mode
  * Use [`fetch`](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API) API to get response, transform [`Response`](https://developer.mozilla.org/en-US/docs/Web/API/Response) into a raw HTTP response and show it in the right panel
  * You can do anything supported by `fetch`
  * The response is **NOT** rendered in the page

About response rendering, Fetch mode will not render response. Or do you really want Fetch mode to render it?
> Rendering in Fetch mode is possible by using `document.write`, but I think the behavior is not perfect for me.
> That is why I prefer to not support it here.

> **Every time we press the EXECUTE button, the new panel will auto-load the last HTTP raw request into the bigtext area.**
> **When we are in the new panel, the EXECUTE button can send the raw HTTP request.**

Sorry that I cannot imagine the complete UI flow.
I think EXECUTE button is used to perform a request, not to load request.

> **And I think maybe hackbar can move some encoding / decoding stuff into the right-click mouse panel.**
> **It can save some space on the top bar and it's more user-friendly than the top bar.**

This is a good advice.
But I think it will not land in next release since it is needed to be designed.

BTW, I'm also not a native English speaker. :laughing:
I use English in GitHub just because I hope that others can know what we are talking about.

**Comment by 0140454** [comment]
Oh, so what you want is converting request from normal mode and auto-filling it in Fetch mode
Just like the following?

In normal mode
![image](https://user-images.githubusercontent.com/1191368/193454325-495cd13f-541c-4582-9cda-d8b1ad8d2282.png)

After change to Fetch mode
![image](https://user-images.githubusercontent.com/1191368/193454135-6dccbae1-caf6-48d5-a23e-7e3dc9b565e4.png)

And no matter what changes made in the request, we can also see the changes after switching to another mode.
But the limitation of HTTP verbs / Content-type is only removed in Fetch mode.

**Comment by 0140454** [comment]
I have implemented a new mode called `Raw mode`.

You can build the latest version using `mv3` branch or just download pre-built version from Release page.

Note that the minimum required Chrome version is 107, you need to wait for Google or just modify `manifest.json` to decrease the limit to 106.

**Comment by 0140454** [comment]
I have implemented a new mode called `Raw mode`.

You can build the latest version using `mv3` branch or just download pre-built version from Release page.

Note that the minimum required Chrome version is 107, you need to wait for Google or just modify `manifest.json` to decrease the limit to 106.

If there is any problem or suggestion, you can report it here. Or, I will close this issue after a while.

**Comment by 0140454** [comment]
I have implemented a new mode called `Raw mode`.

You can build the latest version using `mv3` branch or just download pre-built version from Release page.

BTW, since this [issue](https://bugs.chromium.org/p/chromium/issues/detail?id=1024211), I set `minimum_chrome_version` to 107 in `manifest.json` for avoiding someone install it on Chrome <= 106.
Therefore, you need to wait for Google releasing Chrome 107, or directly modify `manifest.json` to remove the limit if you want to try it immediately.

If there is any problem or suggestion, you can report it here. Or, I will close this issue after a while.

**Comment by 0140454** [comment]
> I don't know if this behavior is by design. Maybe can add a feature that will auto-render / show result in the browser's tab page.

Yes, it is by design now.
Since rendering is finished in extension page, I am afraid that there is some malicious code in rendered response, e.g. communicating with extension and sending other tab's request data to remote.
However, I think it may be able to mediated by checking connection issuer. I will take this advice into account latter.

> I don't know if the browser cache will affect the hackbar's result, from now It seems the cache won't affect hackbar's `EXECUTE` result.

Currently, caching is disabled for any request issued in `Raw` mode.

> If so, maybe can add a feature that can disable browser's cache.

Sorry that I don't understand your meaning. Since caching is disabled now, do you mean that you want a switch to enable caching? If so, may you describe your scenario because I think caching may affect pentester's judgement so that it should be disabled?

**Comment by 0140454** [comment]
> if `safe mode` is enabled, the page will be rendered in safe tabs
if it's not enabled, the page will be rendered in current tab

To render received response, there may be some solutions like the following:
- Write HTML directly via `document.open` and `document.write`
  Since the origin is still the original one, I think it is totally unsafe.
  Scneario:
  1. Go to `https://www.secret.com`
  2. Render response, which contains code accessing to `document.cookie`, from `https://www.malicious.com`
- Go to `about:blank`, and then call `document.xxx` like the first solution
  It seems that I cannot send necessary information for rendering, e.g. HTML, to injected content script.
  Therefore, I don't implement this solution.
- Go to `chrome-extension://yyy/render.html`, where `yyy` is HackBar extension ID, and then call `document.xxx`
  If response contains code like `chrome.runtime.connect`, it can communicate with HackBar service worker, get some sensitive request data and then send back to remote server.
  Currently, I choose this solution because I may be mediated by checking connection creator (not yet implemented). Once implementation finished, I think we can make it automatically rendering response.

> if safe mode is a good idea, we can add more stuff in it like disable web RTC to prevent real IP address leak

It's a good idea.

> maybe safe mode can be a page that contains many switches so we can set the safe feature we want separately

What safe features do you want to have? Since `chrome-extension://yyy/` already have some limitations, maybe what you want already exists.

**Comment by 0140454** [comment]
> `go to about:blank and call document.xxx` will open new tabs

In fact, all solutions I mentioned use the same tab, not new one.

> I haven't learned JS so I don't know if there is any other Malicious JS code that can cause security flaws

Oh, I forgot that it is impossible to execute malicious inline code in Manifest Version 3 because it is restricted by CSP.
So, there may be no security flaws now.

However, if we use solution 1, it will resend the original tab request (not the request in Raw mode) on clicking refresh button. I think it is not a good experience for user.

> It seems in the `chrome-extension://yyy/asdf.html`, other chrome plugins will be disabled

No matter what solution we use, we finally call `document.open` and `document.write` to render the response.
I think other chrome plugins (e.g. [JSON Viewer](https://chrome.google.com/webstore/detail/json-viewer/gbmdgpbipfallnflgajpaliibnhdgobh)) will not works as expected even if we don't use `chrome-extension://...` because related content scripts are removed and there is no timing for inserting scripts again.

If we want to solve this known issue, we need to figure out another solution, which is not mentioned above.

**Comment by 0140454** [comment]
Here are some misunderstanding.

> if we use solution 1: we can't refresh the page and the other plugin will retain the first response status no matter how much we press the `EXECEUTE` button

We can refresh the page but it sends the original request, and the plugin will be re-triggered.

Example:
1. Go to `https://www.google.com`
2. Execute a request `https://www.example.com` and render it
3. Click refresh button
4. It shows response from `https://www.google.com`, not from `https://www.example.com`

> if we use solution 2: every `EXECUTE` response will render in the same new tab and the other plugins will retain the first `EXECUTE`'s response status, but it seems hard to implement.

In fact, solution 2 cannot be implemented.

In theory, after executing a request `https://www.example.com`, I expect that it performs the following steps to render:
1. Go to `about:blank`
2. HackBar injects render script into the page, and it will register a listener to receive some data for rendering
3. HackBar service worker send data to the page
4. After receiving data, render script starts to render it

However, it failed in step 2.

> I don't know if chrome provided any API that can inform the plugin refresh status

Unfortunately, there is no such API, otherwise I also want to trigger other plugins to make HackBar more perfect :(

> is that possible to add HTML highlight in the response panel?

It cannot be done with current UI framework. However, I can try to introduce it via another way.

But I think it is out of this issue's scope. If you really want it, you can create a new issue for it.

**Comment by 0140454** [comment]
You can checkout `testing` branch and build it, then try solution 1 and 2.

Solution 1:
1. Run `php -S 127.0.0.1:8888`
2. Go to `https://www.example.com`
3. Execute `http://127.0.0.1:8888/solution1.php` and render it
4. Click refresh button

Solution 2:
1. Run `php -S 127.0.0.1:8888`
2. Go to `https://www.example.com`
3. Execute `http://127.0.0.1:8888/solution2.php` and render it
4. Open new tab and go to `chrome://extensions/`, you will find there is an error in HackBar
   ![image](https://user-images.githubusercontent.com/1191368/198601015-7aee025a-fb30-4828-8cd3-ba2010381244.png)

**Comment by 0140454** [comment]
> solution 1 might not be perfect, but I think it is the closest to a perfect solution for now

Okay, I think you are right if we consider HackBar's main target audience is pentester.

I will change it to solution 1 and support auto-rendering (enabled by default). But auto-rendering can be opt-out via a switch.

> check if `RAW MODE`'s `Host` is empty

Although it improves user experience, I think I will not implement the two function you mentioned. Here is the reason:
- `LOAD` and `EXECUTE` can be triggered via hotkey
- A function / field should only do its own job to make it maintainable

> Another problem is that `Ctrl+f` cant search in the current `RAW MODE`, I don't know if we can add a search box in RAW MODE and it would be great if this grep box can support regex which is very useful in HTTP crawler testing

I can try to do this. You can create a new issue for it.

**Comment by 0140454** [comment]
Oops, I found there is some problem if we use solution 1: `base` tag may be not respected by the browser. This cause that `img` tag or other resouce cannot be rendered correctly since browser is unable to use correct URL to obtain them.

> so we have to scroll down to check out the HTML content or just press the RENDER button again to check out the render of the result, which is a little inconvenient compared with Basic MODE which could directly see the result on the right side.

If refresh is not a problem to you and the point you care is auto-rendering, I think I prefer to continue to use solution 3.

Do you have other thought?

**Comment by 0140454** [comment]
> I guess is the RAW MODE’s implementation is difference than BASIC MODE?

Yes, their implementation are different.

> btw i forgot to report the solution 3 have some render problem in some pages too, but I haven’t take further test because I thought if RAW MODE response behavior can be like BASIC MODE ( not jump into chrome-extensions://xxx/render.html but the normal url just work well ) this problem will be solved too, now the things seems become more complicated, i guess we can just let it be🥲. maybe one day in the future we will get new idea to solve it perfectly

Indeed, there must be something cannot be rendered as expected since we use `document.write` to write HTML.

Just like you said, let it go until we get a new idea about rendering. :(

**Comment by 0140454** [comment]
Related commit pushed
