### ISSUE TITLE
[ Feature Request ] Can HackBar add a switcher that can disable / enable JavaScript?

### ISSUE THREAD

**Issue by NEX-S** [0140454/hackbar#21]
maybe HackBar can add a switcher that can disable / enable Javascript, this will be very useful because
+ sometimes the js-popup window can block our sight of important info on the page
+ js might have some harmful behavior such as Leak the pentester's Real IP through Web RTC / honeypot request danger APIs
+ Bypass some JavaScript check when uploading files / XSS ...
+ etc...

:rabbit:

**Comment by 0140454** [comment]
> sometimes the js-popup window can block our sight of important info on the page

I think there are some extension have this functionality, and it is out-of-scope.

> js might have some harmful behavior such as Leak the pentester's Real IP through Web RTC / honeypot request danger APIs

After thinking, I will not implement because it is required to add some help text to inform user that HackBar insert something into raw response (if in Raw mode).

> Bypass some JavaScript check when uploading files / XSS

This may be fulfilled by making Response panel editable so that you can remove related JavaScript check and then render it.
