### ISSUE TITLE
POST submission data error

### ISSUE THREAD

**Issue by chixiaome** [0140454/hackbar#4]
During the wide byte injection process, submitting% df in the POST parameter will cause an error. Please tell me how to solve this problem.It will prompt me URI malformed.
![image](https://user-images.githubusercontent.com/53245410/77225261-85b30080-6ba8-11ea-9b47-a5680917e5af.png)

**Comment by 0140454** [comment]
Thanks for your report.

Since HackBar uses `decodeURIComponent` when rebuilding form to be sent, it will throw an error when you use wide byte.

Possible solution is using the processing logic of `application/json` enctype.
1. Split `A=%df'&B=Hello` into two part `A=%df'&B` and `Hello`
2. Construct a `text/plain` form with a input whose name is `A=...` and value is `He...`
3. After submitting this form, overwrite `content-type` header with `application/x-www-form-urlencoded`

I may publish a new version in recent days. If you cannot wait the release, you can modify code according to the above description.

**Comment by 0140454** [comment]
Need another solution

**Comment by 0140454** [comment]
New enctype for raw data is added in commit f014baea1d14063dafd1a73eea3df277d191171a.
